name = "MyFirstPackage"
uuid = "7516325f-1f67-4bc6-ab72-7002fe4ae7d0"
authors = ["Changkey Culing"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
